spring:
  profiles:
    # 启动环境加载，同时加载两个的写法：common,prod  优先级左>右
    active: dev
    # active: test
    # active: prod

  # ================ 公共配置(优先级低于application-xxx.yml)  ================
  # servlet配置
  servlet:
    # 单文件大小限制1024M，避免文件上传时因为文件过大而被限制
    multipart:
      max-file-size: 1024MB    #是单个文件大小
      max-request-size: 1024MB #是设置总上传的数据大小

  #请求路径匹配
#  mvc:
#    static-path-pattern: /images/**
  # 静态文件路径映射
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${spring.upload-config.root_folder}

  # 文件上传相关配置
  upload-config:
    # 文件保存的根目录，所有文件都保存在这个目录下
    root_folder: /upload-file
    # http路由前缀，用于向前台暴露文件url
    http_prefix: /upload

# mybatis配置
mybatis:
  configuration:
    #  控制打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #  开启下划线转驼峰
      # map-underscore-to-camel-case: true
##jwt配置
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: restapiuser
  # 过期时间，时间戳
  expiresSecond: 1895047089
        
        